#!/bin/sh
##################################################################################################
#
#					 ____  _   _    _    ____ ___     _____   _    ____  _____ 
#					/ ___|| | | |  / \  |  _ \_ _|   |__  /  / \  |  _ \| ____|
#					\___ \| |_| | / _ \ | | | | |_____ / /  / _ \ | | | |  _|  
#					 ___) |  _  |/ ___ \| |_| | |_____/ /_ / ___ \| |_| | |___ 
#					|____/|_| |_/_/   \_\____/___|   /____/_/   \_\____/|_____|
#
#					https://github.com/ShadiZade
#					key-handler
#					sxiv external keybindings script
#
###################################################################################################
####### symlink location: ~/.config/sxiv/ #########################################################

move () {
	loc=$(ls -1 "$HOME/Pictures/mobile/3-finished" | rofi -dmenu -i -p 'choose folder')
	[ -z "$loc" ] || mv -vn -- "$file" "$HOME/Pictures/mobile/3-finished/$loc"
}

describe () {
	ext=$(echo "$file" | awk -F '.' '{print $NF}')
	newname="$(fd 'jpg|jpeg|png|gif|webp|jxl|jpg_large|svg' $(pwd) | awk -F '/' '{print $NF}' | rofi -dmenu -i -p 'rename image')"
	[ -z "$newname" ] || mv -vn -- "$file" "$newname"."$ext"
}

while read file
do
        case "$1" in
        "C-p")
                rt "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-z")
       		move ;;
        "C-d")
       		describe ;;
	"C-q")
       		mv -vn -- "$file" . ;;
        esac
done

