#!/bin/bash
##################################################################################################
#
#					 ____  _   _    _    ____ ___     _____   _    ____  _____ 
#					/ ___|| | | |  / \  |  _ \_ _|   |__  /  / \  |  _ \| ____|
#					\___ \| |_| | / _ \ | | | | |_____ / /  / _ \ | | | |  _|  
#					 ___) |  _  |/ ___ \| |_| | |_____/ /_ / ___ \| |_| | |___ 
#					|____/|_| |_/_/   \_\____/___|   /____/_/   \_\____/|_____|
#
#					https://github.com/ShadiZade
#					key-handler
#					sxiv external keybindings script
#
###################################################################################################
####### symlink location: ~/.config/sxiv/ #########################################################
source /home/oak/Repositories/scripts/essential-functions.sh 

sort () {
    loc="$(eza --no-quotes -1Daa "$(pwd)" | rofi -dmenu -i -p 'choose folder')"
    [ -z "$loc" ] || mv -vn -- "$file" "$(pwd)/$loc"
}

describe () {
    ext=$(echo "$file" | awk -F '.' '{print $NF}')
    killall dunst
    notify-send -t 10000000 "Old name:" "$file"
    newname="$(fd 'jpg|jpeg|png|gif|webp|jxl|jpg_large|svg' "$(pwd)" | awk -F '/' '{print $NF}' | rofi -dmenu -i -p 'rename image')"
    newname="$(~/Repositories/scripts/kebabization.sh "$newname"; cat "$HOME/.local/share/user-scripts/kebab")"
    [ -z "$newname" ] || (mv -vn -- "$file" "$newname"."$ext"
			  killall dunst
			  notify-send -t 3000 "File renamed:" "$newname.$ext")
}

move () {
    mv -vn -- "$file" .
}

copyhere () {
    cp -vn -- "$file" .

}

trash () {
    move-to-trash "$file"
}

copypath () {
    realpath "$file" | tr -d '\n' | xclip -selection clipboard
}


showinfo () {
    filename="$(basename "$file")"
    geometry="$(identify -format '%wx%h' "$file[0]")"
    filetype="$(mimetype -db "$file")"
    datec="$(exiftool -q "$file" | grep "Create Date" -m 1 | ifne sed 's/Create Date                     : //;')"
    filesize="$(du -h "$file" | awk '{print $1}')"
    killall dunst
    notify-send -t 20000 "File info:" "${filename}\n${filesize}\n${filetype}\n${geometry}\n${datec:-––NO DATE––}"
}


edit () {
    echolor yellow ":: image ““$file”” opened using PhotoFlare"
    photoflare "$file" 2> /dev/null 
}

editgimp () {
    echolor yellow ":: image ““$file”” opened using GIMP"
    gimp "$file" 2>/dev/null
}

changedate () {
    lasttime="$(stat -c "%y" "$file" | awk -F '.' '{print $1}')"
    currentdate="$(date +"%Y-%m-%d %H:%M:%S")"
    echolor yellow ":: Updated date on image ““$file””"
    echolor yellow-blue ":: ─────── from ““$lasttime”” to ““$currentdate””"
    touch "$file"
    killall dunst
    notify-send -t 7000 "Gentle touch" "${file}\n${lasttime}\n${currentdate}"
}

while read file
do
        case "$1" in
        "C-t")  trash ;;
        "C-p")  copypath ;;
	"C-c")  copyhere ;;
        "C-s")	sort ;;
        "C-d")	describe ;;
	"C-m")  move ;;
	"C-e")  edit ;;
	"C-g")  editgimp ;;
	"C-0")  changedate ;;
	"C-i")  showinfo ;;
        esac
done

