#!/bin/sh
##################################################################################################
#
#					 ____  _   _    _    ____ ___     _____   _    ____  _____ 
#					/ ___|| | | |  / \  |  _ \_ _|   |__  /  / \  |  _ \| ____|
#					\___ \| |_| | / _ \ | | | | |_____ / /  / _ \ | | | |  _|  
#					 ___) |  _  |/ ___ \| |_| | |_____/ /_ / ___ \| |_| | |___ 
#					|____/|_| |_/_/   \_\____/___|   /____/_/   \_\____/|_____|
#
#					https://github.com/ShadiZade
#					key-handler
#					sxiv external keybindings script
#
###################################################################################################
####### symlink location: ~/.config/sxiv/ #########################################################

sort () {
    loc=$(ls -1 "$HOME/Pictures/mobile/3-finished" | rofi -dmenu -i -p 'choose folder')
    [ -z "$loc" ] || mv -vn -- "$file" "$HOME/Pictures/mobile/3-finished/$loc"
}

describe () {
    ext=$(echo "$file" | awk -F '.' '{print $NF}')
    killall dunst
    notify-send -t 10000000 "Old name:" "$file"
    newname="$(fd 'jpg|jpeg|png|gif|webp|jxl|jpg_large|svg' $(pwd) | awk -F '/' '{print $NF}' | rofi -dmenu -i -p 'rename image')"
    newname="$(~/Repositories/scripts/kebabization.sh "$newname"; cat ~/.kebab)"
    [ -z "$newname" ] || (mv -vn -- "$file" "$newname"."$ext"
			  touch "$newname"."$ext"
			  killall dunst
			  notify-send -t 3000 "File renamed:" "$newname.$ext")
}

move () {
    mv -vn -- "$file" .
}

copyhere () {
    cp -vn -- "$file" .

}

trash () {
    rt "$file"
}

copypath () {
    echo -n "$(pwd)/$file" | sed 's|/\./|/|g' | xclip -selection clipboard
}


edit () {
    photoflare "$file"
}

editgimp () {
    gimp "$file"
}

changedate () {
    touch "$file"
}

while read file
do
        case "$1" in
        "C-t")  trash ;;
        "C-p")  copypath ;;
	"C-c")  copyhere ;;
        "C-s")	sort ;;
        "C-d")	describe ;;
	"C-m")  move ;;
	"C-e")  edit ;;
	"C-g")  editgimp ;;
	"C-0")  changedate ;;
        esac
done

