#!/bin/bash
##################################################################################################
#
#					 ____  _   _    _    ____ ___     _____   _    ____  _____ 
#					/ ___|| | | |  / \  |  _ \_ _|   |__  /  / \  |  _ \| ____|
#					\___ \| |_| | / _ \ | | | | |_____ / /  / _ \ | | | |  _|  
#					 ___) |  _  |/ ___ \| |_| | |_____/ /_ / ___ \| |_| | |___ 
#					|____/|_| |_/_/   \_\____/___|   /____/_/   \_\____/|_____|
#
#					https://github.com/ShadiZade
#					bspwmrc
#					bspwm config
#
###################################################################################################
####### symlink location: ~/.config/bspwm/ ########################################################
source ~/Repositories/scripts/bspwm-theme.sh
source ~/.local/share/user-scripts/current-theme
source ~/Repositories/scripts/essential-functions.sh

cmp -s /etc/hostname <(echo "zookeeper") && xrandr -s 1280x720
pgrep -x sxhkd > /dev/null || sxhkd &
picom --config ~/.config/picom/picom.conf &
xwallpaper --zoom "$lin_wallpaper" &
fcitx5 -d &
copyq &
flameshot &
emacs --daemon &

killall battery-warner.sh
~/Repositories/scripts/battery-warner.sh &

[[ "$battery_warning_on" -eq 0 ]] && {
    notify-send -u critical -t 100000 "BATTERY WARNER OFF" "You will not be notified if the battery level becomes too low".
}

bspc monitor -d 1 2 3 4 5 6 7 8 9

$HOME/.config/polybar/scripts/polybar-launch.sh &
bspc config top_padding 35
bspc config border_width 5
bspc config window_gap 8

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#$lin_color1"
bspc config normal_border_color	 "#$lin_color2"

bspc rule -a Steam state=floating 

bspc rule -a Emacs state=tiled

bspc rule -a photoflare state=fullscreen
bspc rule -a smplayer state=fullscreen
bspc rule -a Sxiv state=fullscreen  
bspc rule -a okular state=fullscreen  
bspc rule -a FreeTube state=fullscreen
bspc rule -a calibre state=fullscreen
bspc rule -a Zathura state=fullscreen
#bspc rule -a Xdg-desktop-portal-gtk state=fullscreen
#bspc rule -a Gimp-2.10 state=fullscreen
