#!/bin/sh
##################################################################################################
#
#					 ____  _   _    _    ____ ___     _____   _    ____  _____ 
#					/ ___|| | | |  / \  |  _ \_ _|   |__  /  / \  |  _ \| ____|
#					\___ \| |_| | / _ \ | | | | |_____ / /  / _ \ | | | |  _|  
#					 ___) |  _  |/ ___ \| |_| | |_____/ /_ / ___ \| |_| | |___ 
#					|____/|_| |_/_/   \_\____/___|   /____/_/   \_\____/|_____|
#
#					https://github.com/ShadiZade
#					bspwmrc
#					bspwm config
#
###################################################################################################
####### symlink location: ~/.config/bspwm/ ########################################################

source ~/Repositories/scripts/bspwm-theme.sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
xwallpaper --zoom "$bspwm_theme_wallpaper" &
fcitx5 -d &
$HOME/.config/polybar/scripts/polybar-launch.sh &
setxkbmap

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         7
bspc config window_gap          12

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		      "#$bspwm_theme_secondary_color"
bspc config focused_border_color	      "#$bspwm_theme_primary_color"

bspc rule -a persepolis state=floating 
bspc rule -a Steam state=floating 
bspc rule -a Howl state=floating 

bspc rule -a Emacs state=tiled

bspc rule -a smplayer state=fullscreen
bspc rule -a Sxiv state=fullscreen  
bspc rule -a okular state=fullscreen  
bspc rule -a FreeTube state=fullscreen
bspc rule -a calibre state=fullscreen
