#!/bin/bash
##################################################################################################
#
#					 ____  _   _    _    ____ ___     _____   _    ____  _____ 
#					/ ___|| | | |  / \  |  _ \_ _|   |__  /  / \  |  _ \| ____|
#					\___ \| |_| | / _ \ | | | | |_____ / /  / _ \ | | | |  _|  
#					 ___) |  _  |/ ___ \| |_| | |_____/ /_ / ___ \| |_| | |___ 
#					|____/|_| |_/_/   \_\____/___|   /____/_/   \_\____/|_____|
#
#					https://github.com/ShadiZade
#					sxhkdrc
#					sxhkd config
#
###################################################################################################
####### symlink location: ~/.config/sxhkd/ ########################################################


############################################# basic bindings

# quit or restart bspwm
super + shift + {q,r}
	bspc {quit,wm -r}

# close or kill program
super + shift + {c,k}
	bspc node -{c,k}

# activate dalek mode
super + shift + Delete
	xkill

# reload sxhkd configs:
super + shift + s
	pkill sxhkd; sxhkd

# volume down/up
super + alt + ctrl + {Down,Up}
	pulsemixer --change-volume {-,+}10

# volume mute/100
super + alt + ctrl + {slash,BackSpace}
	pulsemixer {--toggle-mute,--set-volume 100}

# brightness down/up
super + alt + ctrl + {minus,equal}
	brightnessctl s 40{-,+}

# quodlibet controls
super + alt + ctrl + {space,Right,Prior,Next,0}
	quodlibet {--play-pause,--next,--seek=-00:03,--seek=+00:03,--seek=00:00}

# quodlibet enqueue current
super + alt + ctrl + Left
	$HOME/Repositories/scripts/quodlibet-enqueue.sh

# quodlibet enqueue song
super + alt + ctrl + Return
	$HOME/Repositories/scripts/choose-song.sh

# quodlibet enqueue classical
super + alt + ctrl + asciitilde
	$HOME/Repositories/scripts/choose-classical.sh
	
# clear clipboard
super + shift + BackSpace
	xsel -cb

############################################# window management

# focus the last desktop
super + Escape
	bspc desktop -f last

# focus the previous/next window in the current desktop
super + {j,k}
	bspc node -f {prev.local.!hidden.window,next.local.!hidden.window}

# focus on desktop
super + {1-9}
	bspc desktop -f '^{1-9}'

# send to desktop
super + shift + {1-9}
	bspc node -d '^{1-9}' follow=on

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + ctrl + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# toggle fullscreen
super + f
	bspc node -t fullscreen || bspc node -t tiled

# set windowing mode
super + slash
        ~/Repositories/scripts/window-tiling.sh 

	
############################################# program shortcuts


# rofi
super + q ; a
	rofi -show drun

# terminal
super + q ; s
	pkill dunst; dunst & notify-send -t 1000 'Launcher' 'Launching "kitty"' & kitty

# vivaldi
super + q ; v
	pkill dunst; dunst & notify-send -t 1000 'Launcher' 'Launching "vivaldi"' & vivaldi-stable

# emacs
super + q ; e
	pkill dunst; dunst & notify-send -t 1000 'Launcher' 'Launching "emacs"' & emacsclient -c -a emacs

# quodlibet
super + q ; l
	pkill dunst; dunst & notify-send -t 1000 'Launcher' 'Launching "quodlibet"' & quodlibet

# freetube
super + q ; f
	pkill dunst; dunst & notify-send -t 1000 'Launcher' 'Launching "freetube"' & freetube && pkill dunst

# qbittorrent
super + q ; b
	pkill dunst; dunst & notify-send -t 1000 'Launcher' 'Launching "qbittorrent"' & qbittorrent && pkill dunst

# calibre
super + q ; c
	pkill dunst; dunst & notify-send -t 1000 'Launcher' 'Launching "calibre"' & calibre && pkill dunst

# google-earth-pro
super + q ; r
	pkill dunst; dunst & notify-send -t 1000 'Launcher' 'Launching "google earth pro"' & google-earth-pro && pkill dunst	

# windscribe
super + q ; w
	pkill dunst; dunst & notify-send -t 1000 'Launcher' 'Launching "windscribe"' & windscribe && pkill dunst	

# flameshot
{_,ctrl + }Print
	flameshot {full,gui}






############################################# run scripts

# lockscreen
super + z
	~/Repositories/scripts/lockscreen.sh

# Give QR
super + asciitilde
    ~/Repositories/scripts/give-qr.sh
	
############################################ copy-paste scripts

# emoji
super + a ; e
	rofimoji -a copy

# latin supplement
super + a ; l
	~/Repositories/scripts/language-insertion.sh

# IPA
super + a ; i
	rofimoji -a copy --files "$HOME/Repositories/dotfiles/rofimoji/used-files/ipa/*"

# frequent-words
super + a ; f
	cat ~/.frequent-words | rofi -normalize-match -i -dmenu | tr -d '\n' | xclip -selection clipboard

# wiki-shortcuts
super + a ; w
	export which_shortcuts=wiki-shortcuts; ~/Repositories/scripts/wiki-shortcuts.sh

# afc-shortcuts
super + a ; c
	export which_shortcuts=afc-shortcuts; ~/Repositories/scripts/wiki-shortcuts.sh


############################################ misc

super + b
    mpv "$HOME/.local/share/user-scripts/sounds/bruh.mp3"

super + d
    ~/Repositories/scripts/sound-effects.sh d2a-d2i
super + shift + b
    for j in {1..5}; do killall xdg-desktop-portal; done; ~/Repositories/scripts/sound-effects.sh "jumpy-laser"





# ---------------------------------------------------------------------	
#
# bspwm hotkeys
#

# alternate between the tiled and monocle layout
#super + @space
#	bspc desktop -l next

# send the newest marked node to the newest preselected node
#super + y
#	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest window
#super + g
#	bspc node -s biggest.window


#
# state/flags
#

# set the node flags
#super + ctrl + {m,x,y,z}
#	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
#super + {_,shift + }{h,j,k,l}
#	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
#super + {p,b,comma,period}
#	bspc node -f @{parent,brother,first,second}


# focus the next/previous desktop in the current monitor
# super + bracket{left,right}
#	bspc desktop -f {prev,next}.local


# focus the older or newer node in the focus history
#super + {o,i}
#	bspc wm -h off; \
#	bspc node {older,newer} -f; \
#	bspc wm -h on


#
# preselect
#

# preselect the direction
#super + ctrl + {h,j,k,l}
#	bspc node -p {west,south,north,east}

# preselect the ratio
#super + ctrl + {1-9}
#	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
#super + ctrl + space
#	bspc node -p cancel

# cancel the preselection for the focused desktop
#super + ctrl + shift + space
#	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

