theme_name: 

colors:
  color1:	
    name: 
    hex: 
  color2:
    name: 
    hex: 
  color3:
    name: 
    hex: 
  color4:
    name: 
    hex: 

wallpaper: 
  name: 
  path: 

files:
  rofi: "$HOME/Repositories/dotfiles/rofi/themes/.rasi"
  polybar: "$HOME/Repositories/dotfiles/polybar/themes/.ini"

