theme_name: 

colors:
  color1:
    name: 
    hex: 
  color2:
    name: 
    hex: 
  color3:
    name: 
    hex: 
  color4:
    name: 
    hex: 
  color5:
    name:
    hex: 
  
wallpaper: 
  name: 
  path: "$HOME/.local/share/user-scripts/wallpapers/"

files:
  rofi: "$HOME/Repositories/dotfiles/rofi/themes/.rasi"
  polybar: "$HOME/Repositories/dotfiles/polybar/themes/.ini"
  dunst: "$HOME/Repositories/dotfiles/dunst/themes/"
