#!/bin/zsh
##################################################################################################
#
#					 ____  _   _    _    ____ ___     _____   _    ____  _____ 
#					/ ___|| | | |  / \  |  _ \_ _|   |__  /  / \  |  _ \| ____|
#					\___ \| |_| | / _ \ | | | | |_____ / /  / _ \ | | | |  _|  
#					 ___) |  _  |/ ___ \| |_| | |_____/ /_ / ___ \| |_| | |___ 
#					|____/|_| |_/_/   \_\____/___|   /____/_/   \_\____/|_____|
#
#					https://github.com/ShadiZade
#					.zshrc
#					zsh config
#
###################################################################################################
####### symlink location: ~/.config/zsh/ ##########################################################
# cd aliases
## Aquire (YOU KNOW WHAT? FUCK YOU. *REFORMS YOUR SPELLING*)
alias cdq="cd ~/Aquire && ll"
alias cdqb="cd ~/Aquire/books && ll"
alias cdqm="cd ~/Aquire/music && ll"
alias cdqp="cd ~/Aquire/pictures && ll"
alias cdqv="cd ~/Aquire/video && ll"
alias cdqt="cd ~/Aquire/torrents/ && ll"
## Desktop
alias cdk="cd ~/Desktop && ll"
alias cdkt="cd ~/Desktop/try && ll"
## Local
alias cdl="cd ~/.local/mobile/Internal\ shared\ storage/Home && ll"
alias cdt="cd ~/.local/share/Trash/files && lln -a --time=changed --sort=changed && du -sh"
## Downloads
alias cdd="cd ~/Downloads && lln"
## Pictures
alias cdp="cd ~/Pictures && ll"
alias cdpd="cd ~/Pictures/design/ && ll"
## Misc
alias cdm="cd ~/Misc && ll"
alias cdmb="cd ~/Misc/Backups && ll"
alias cdmbv="cd ~/Misc/Backups/video/ && ll"
alias cdmbvt="cd ~/Misc/Backups/video/torrents/ && lln"
alias cdmbvi="cd ~/Misc/Backups/video/imdb/ && ll"
alias cdmbvd="cd ~/Misc/Backups/video/donefiles/ && cat-donefiles"
alias cdmbp="cd ~/Misc/Backups/private-scripts/ && ll"
alias cdmr="cd ~/Misc/research-topics && ll"
alias cdmn="cd ~/Misc/notes && ll"
alias cdmo="cd ~/Misc/org/ && ll"
alias cdmd="cd ~/Misc/diary/ && ll"
alias cdmc="cd ~/Misc/cooking && ll"
## Movies
alias cdmov="cd ~/Movies && ll"
## Books
alias cdb="cd ~/Books"
alias cdba="cd ~/Books/add && delete-opf; ll"
alias cdbx="cd ~/Books/xdone/; ll"
## Config
alias cdc="cd ~/.config"
## Study
alias cds="cd ~/Study && ff"
alias cdsl="cd ~/Study/languages && fzf-choose-directory && ll"
alias cdslc="cd ~/Study/languages/chinese/ && ll"
alias cdsp="cd ~/Study/programming && fzf-choose-directory && ll"
alias cdsu="cd ~/Study/uni/ && ll"
alias cdsuc="cd ~/Study/uni/courses && fzf-choose-directory && ll"
alias cdsm="cd ~/Study/marxism/ && fzf-choose-directory && ll"
## TV
alias cdtv="cd ~/TV && fzf-choose-directory && ll"
## Repositories
alias cdr="cd ~/Repositories/ && fzf-choose-directory && ll"
alias cdrs="cd ~/Repositories/scripts && ll"
alias cdrd="cd ~/Repositories/dotfiles && ll"
alias cdrcd="cd ~/Repositories/communist-calendar/dates/ && ll"
## Archives
alias cda="cd ~/Archives && ll"
alias cdas="cd ~/Archives/Socialist && ll"
alias cdasp="cd ~/Archives/Socialist/people && ll"
alias cdasc="cd ~/Archives/Socialist/countries && l"
alias cdap="cd ~/Archives/Palestine && ll"
alias cdar="cd ~/Archives/Personal && ll"
alias cdard="cd ~/Archives/Personal/documents/ && ll"
alias cdao="cd ~/Archives/Other && ll"
alias cdaos="cd ~/Archives/Other/safekeeping/ && ll"
## Wallpapers
alias cdwall="cd /usr/share/wallpapers/use && ll"
## Excluding
alias cde="cd ~/Excluding/ && ll"
alias cdep="cd ~/Excluding/podcasts && lln"
alias cdey="cd ~/Excluding/ytvid && lln"
## Projects
alias cdj="cd ~/Projects"
alias cdjw="cd ~/Projects/wiki && ll"
alias cdjr="cd ~/Projects/writings/ && ll"
alias cdjm="cd ~/Projects/motif/ && ll"
alias cdjt="cd ~/Projects/translation/ && ll"
## Holding
alias cdh="cd ~/Holding/ && lln"
alias cdhs="cd ~/Holding/screenshots/ && ll"
## Videos
alias cdv="cd ~/Videos/ && ll"
## Documents
alias cdo="cd ~/Documents/ && ll"
alias cdol="cd ~/Documents/lisan-al-3arab/ && ll"

# translation
alias zhen="command trans -b zh:en"
alias enzh="command trans -b en:zh"
alias deen="command trans -b de:en"
alias ende="command trans -b en:de"
alias esen="command trans -b es:en"
alias enes="command trans -b en:es"
alias ruen="command trans -b ru:en"
alias enru="command trans -b en:ru"
alias laen="command trans -b la:en"
alias enla="command trans -b en:la"
alias iten="command trans -b it:en"
alias enit="command trans -b en:it"

# list
alias l="eza --icons --sort=ext --group-directories-first"
alias ll="eza -l --icons --no-user --time-style=iso --sort=ext --group-directories-first --color-scale all"
alias lnl="eza -l --icons --no-user --time-style=iso --sort=name --color-scale all"
alias lla="eza -la --icons --no-user --group-directories-first --sort=ext --time-style=iso --color-scale all"
alias lln="eza -l --icons --no-user --time-style=iso --sort=newest --color-scale all"
alias lls="eza -l --icons --no-user --time-style=iso --sort=size --group-directories-first --color-scale all"
alias llt="eza -l --icons --no-user --time-style=iso --sort=ext --group-directories-first --color-scale all --tree"
alias llg="eza -l --icons --no-user --time-style=iso --sort=ext --group-directories-first --color-scale all --git"

# package management
alias pacs="sudo pacman -S "
alias pacrsc="sudo pacman -Rsc"
alias pacr="sudo pacman -Rns"
alias pacss="pacman -Ss"
alias pacsi="pacman -Si"
alias yays="yay --removemake -S"
alias yayss="yay -Ssa"
alias yaysi="yay -Si"
alias yaysc="yay -Sc"
alias syu="sudo pacman -Syu"
alias sua="yay --removemake -Sua"
alias tree="pactree -r "
alias align-mirrors="sudo pacman-mirrors --fasttrack && sudo pacman -Syyu"

# ebooks
alias cdset="cd src/epub/text"


# git
alias '..s'="git status"
alias '..d'="git diff"
alias '..p'="git push -u origin master"
alias '..m'="git push -u origin main"

# scripts 
alias get-image="~/Repositories/scripts/extract-pdf-image.sh"
alias ytm="remove_p='n' ~/Repositories/scripts/ytmp3.sh"
alias ytr="remove_p='y' ~/Repositories/scripts/ytmp3.sh"
alias ytv="~/Repositories/scripts/ytvid.sh"
alias chcover="~/Repositories/scripts/chcover.sh"
alias newscript='which="script" ~/Repositories/scripts/new-micro.sh '
alias newsolution='which="solution" ~/Repositories/scripts/new-micro.sh '
alias newpbmodule='which="polybar-module" ~/Repositories/scripts/new-micro.sh '
alias newfont="~/Repositories/scripts/font-downloader.sh"
alias newmotif="~/Repositories/scripts/newmotif.sh"
alias tess='~/Repositories/scripts/tess.sh'
alias fw='~/Repositories/scripts/frequent-words.sh'
alias tf='~/Repositories/scripts/music-tagger.sh'
alias zas='~/Repositories/scripts/active-study.sh'
alias mvk="~/Repositories/scripts/mv-kebab.sh"
alias mvkr="~/Repositories/scripts/roll-thru-kebab.sh"
alias obo="~/Repositories/scripts/one-by-one.sh"
alias tagger="~/Repositories/scripts/tagger.sh"
alias gv="~/Repositories/scripts/convert-to-mp4.sh"
alias tn="~/Repositories/scripts/takenote.sh"
alias scr="~/Repositories/scripts/scientifier.sh"
alias cf="~/Repositories/scripts/copy-full-path.sh"
alias λ="~/Repositories/scripts/OpenShennong.sh"
alias knife='~/Repositories/scripts/kebab-knife.sh'


# files
alias ’e="emacs -nw ~/Repositories/dotfiles/emacs/init.el"
alias ’k="emacs -nw ~/Repositories/dotfiles/kitty/kitty.conf"
alias ’z="emacs -nw ~/Repositories/dotfiles/zsh/zshrc"
alias ’za="emacs -nw ~/Repositories/dotfiles/zsh/aliases"
alias ’zf="emacs -nw ~/Repositories/dotfiles/zsh/functions"
alias ’ze="emacs -nw ~/Repositories/dotfiles/zsh/extra"
alias ’zv="emacs -nw ~/Repositories/dotfiles/zsh/variables"
alias ’b="emacs -nw ~/Repositories/dotfiles/bspwm/bspwmrc"
alias ’s="micro ~/Repositories/dotfiles/sxhkd/sxhkdrc"
alias ’p="emacs -nw ~/Repositories/dotfiles/polybar/config.ini"
alias ’tc="emacs -nw ~/Repositories/scripts/bspwm-theme.sh"
alias ’tp="~/Repositories/scripts/theme-picker.sh"
alias ’cl="emacs -nw ~/Misc/cooking/cooklist.org"
alias ’cp="emacs -nw ~/Misc/cooking/potential.org"

# misc aliases
alias '..'="cd .. && ll"
alias '..2'="cd ../.."
alias '..3'="cd ../../.."
alias rdol="rdo dolphin ."
alias m="micro"
alias e="emacs -nw "
alias sm="sudo micro"
alias q="source ~/.config/zsh/.zshrc"
alias qq="clr; cd; terminal-art"
alias qqq="clr; cd; source ~/.config/zsh/.zshrc"
alias xx="xdg-open"
alias mk="mkdir -pv"
alias fd="fd -i"
alias cp="cp -iv"
alias mv='mv -iv'
alias rm='rm -iv'
alias rmdir='rmdir -v'
alias grep='grep --color=auto -is'
alias window-name="xprop WM_CLASS"
alias clr="printf '\033[2J\033[3J\033[1;1H'"
alias sudo='sudo '
alias memuse='df | grep sda1 | awk "{print \$5}" '
alias ,,='trans -b'
alias yd='calc "$(date +"%Y")-$1"'
alias llwc="ll | wc -l"
alias back="~/Repositories/scripts/back/backmaster.sh"
alias morse="morse-x -f 350"
alias z="rdo zathura"
alias trash-clear="rm -rf ~/.local/share/Trash/files/*"
alias xvs="xv ~/Holding/screenshots"
alias xsc="xclip -selection clipboard"
alias xscn="tr -d '\n' | xclip -selection clipboard"
alias suben="subdl --interactive --download=query --lang=eng"
alias subar="subdl --interactive --download=query --lang=ara"
alias pf="photoflare"
alias sxiv="sxiv -a"
alias bp="buku -p"
alias ba="buku -a"
alias ytvv="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --no-mtime --embed-chapters"
alias ytmm="yt-dlp --format bestaudio --no-mtime --extract-audio --audio-format mp3"
alias ytrr="yt-dlp --format bestaudio --no-mtime --extract-audio --audio-format mp3 --sponsorblock-remove all"
alias duh="du -h"
alias rq="R -q -f "
alias rqq="R -s -f "
alias Q="R -s"
alias o="rdo okular"
alias cal="cal --color=always -m"
alias f="fzf-choose-directory && ll"
alias f~='hide_flag="-a"; f; hide_flag=""'
alias ff~='hide_flag="-a"; ff; hide_flag=""'
alias →="rsync -Paru" 
