#!/bin/zsh
##################################################################################################
#
#					 ____  _   _    _    ____ ___     _____   _    ____  _____ 
#					/ ___|| | | |  / \  |  _ \_ _|   |__  /  / \  |  _ \| ____|
#					\___ \| |_| | / _ \ | | | | |_____ / /  / _ \ | | | |  _|  
#					 ___) |  _  |/ ___ \| |_| | |_____/ /_ / ___ \| |_| | |___ 
#					|____/|_| |_/_/   \_\____/___|   /____/_/   \_\____/|_____|
#
#					https://github.com/ShadiZade
#					.zshrc
#					zsh config
#
###################################################################################################
####### symlink location: ~/.config/zsh/ ##########################################################
# cd aliases
## Aquire (YOU KNOW WHAT? FUCK YOU. *REFORMS YOUR SPELLING*)
alias cdq="cd ~/Aquire && fzf-dir && ll"
alias cdqb="cd ~/Aquire/books && ll"
alias cdqm="cd ~/Aquire/music && ll"
alias cdqp="cd ~/Aquire/pictures && ll"
alias cdqv="cd ~/Aquire/video && ll"
## Athenaeum
alias cdae="cd ~/Athenaeum/add/ && ll"
## Desktop
alias cdk="cd ~/Desktop && ll"
alias cdkt="cd ~/Desktop/try && ll"
## Local
alias cdls="cd ~/.local/share/ && fzf-dir && ll"
alias cdlsu="cd ~/.local/share/user-scripts && ll"
alias cdlm="cd ~/.local/mobile/Internal\ shared\ storage/Home && ll"
alias cdlmd="cd ~/.local/mobile/Internal\ shared\ storage/Download && ll"
alias cdlmp="cd ~/.local/mobile/Internal\ shared\ storage/Pictures && ll"
alias cdlmc="cd ~/.local/mobile/Internal\ shared\ storage/DCIM/Camera && ll"
alias cdlog="cd ~/.local/logs/ && ff"
## Local
alias cdt="cd ~/.local/share/Trash/files && lln -a --time=changed --sort=changed && du -sh"
## Downloads
alias cdd="cd ~/Downloads && lln"
## P2P
alias cd2="cd ~/P2P/ && ll"
alias cd2u="cd ~/P2P/.unfinished/ && ll"
## Pictures
alias cdp="cd ~/Pictures && ff"
alias cdpd="cd ~/Pictures/design/ && ll"
## Misc
alias cdm="cd ~/Misc && ll"
alias cdmb="cd ~/Misc/Backups && ll"
alias cdmbv="cd ~/Misc/Backups/video/ && ll"
alias cdmbvt="cd ~/Misc/Backups/video/torrents/ && lln"
alias cdmbvi="cd ~/Misc/Backups/video/imdb/ && ll"
alias cdmbvd="cd ~/Misc/Backups/video/donefiles/ && cat-donefiles"
alias cdmr="cd ~/Misc/research-topics && ll"
alias cdmn="cd ~/Misc/notes && ll"
alias cdmo="cd ~/Misc/org/ && ll"
alias cdmd="cd ~/Misc/diary/ && ll"
alias cdmc="cd ~/Misc/cooking && ll"
## Movies
alias cdf="cd ~/Films && ll"
## Books
alias cdb="cd ~/Books"
alias cdba="cd ~/Books/xadd && delete-opf; ll"
alias cdbx="cd ~/Books/xdone/; ll"
## Config
alias cdc="cd ~/.config"
## Study
alias cds="cd ~/Study && ff"
alias cdsl="cd ~/Study/languages && fzf-dir && ll"
alias cdslc="cd ~/Study/languages/chinese/ && ll"
alias cdsb="cd ~/Study/biology && fzf-dir && ll"
alias cdsp="cd ~/Study/programming && fzf-dir && ll"
alias cdsu="cd ~/Study/uni/ && ll"
alias cdsuc="cd ~/Study/uni/courses && ff"
alias cdsul="cd ~/Study/uni/lab && fzf-dir && ll"
alias cdsm="cd ~/Study/marxism/current/ && ff"
alias cdsa="cd ~/Study/academia/ && ff"
## TV
alias cdtv="cd ~/TV && fzf-dir && ll"
## Repositories
alias cdr="cd ~/Repositories/ && fzf-dir && ll"
alias cdrs="cd ~/Repositories/scripts && ll"
alias cdrd="cd ~/Repositories/dotfiles && ll"
alias cdrcd="cd ~/Repositories/communist-calendar/dates/ && ll"
alias cdrp="cd ~/Repositories/private/ && ll"
## Archives
alias cda="cd ~/Archives && ff"
alias cdas="cd ~/Archives/Socialist && ll"
alias cdasp="cd ~/Archives/Socialist/people && ll"
alias cdasc="cd ~/Archives/Socialist/countries && l"
alias cdap="cd ~/Archives/Palestine && ll"
alias cdar="cd ~/Archives/Personal && ll"
alias cdard="cd ~/Archives/Personal/documents/ && ll"
alias cdao="cd ~/Archives/Other && ll"
alias cdaos="cd ~/Archives/Other/safekeeping/ && ll"
## Wallpapers
alias cdwall="cd /usr/share/wallpapers/use && ll"
## Excluding
alias cde="cd ~/Excluding/ && ll"
alias cdep="cd ~/Excluding/podcasts && lln"
alias cdey="cd ~/Excluding/ytvid && lln"
## Projects
alias cdj="cd ~/Projects && ff"
alias cdjm="cd ~/Projects/misc/ && ff"
alias cdja="cd ~/Projects/academia/ && fzf-dir"
alias cdjw="cd ~/Projects/writings/ && ll"
alias cdjwa="cd ~/Projects/writings/articles/ && ll"
alias cdjwp="cd ~/Projects/writings/poetry/ && ll"
alias cdjb="cd ~/Projects/book-restoration/current/ && fzf-dir && ll"
alias cdjt="cd ~/Projects/translation/ && fzf-dir && ll"
alias cdjc="cd ~/Projects/rcsc/ && ff"
## Holding
alias cdh="cd ~/Holding/ && lln"
alias cdhs="cd ~/Holding/screenshots/ && ll"
## Videos
alias cdv="cd ~/Videos/ && ll"
alias cdvc="cd ~/Videos/clips/ && ll"
## Documents
alias cdo="cd ~/Documents/ && ll"
alias cdon="cd ~/Documents/newsletters/ && fzf-dir && ll"
alias cdoc="cd ~/Documents/clippings/ && ll"
alias cdop="cd ~/Documents/papers/ && ll"
# translation
alias zhen="command trans -b zh:en"
alias enzh="command trans -b en:zh"
alias deen="command trans -b de:en"
alias ende="command trans -b en:de"
alias esen="command trans -b es:en"
alias enes="command trans -b en:es"
alias ruen="command trans -b ru:en"
alias enru="command trans -b en:ru"
alias laen="command trans -b la:en"
alias enla="command trans -b en:la"
alias iten="command trans -b it:en"
alias enit="command trans -b en:it"
alias pten="command trans -b pt:en"
alias enpt="command trans -b en:pt"

# list
alias l="cpfg; eza --icons --sort=ext --group-directories-first"
alias ll="cpfg; eza --no-quotes -lX --icons --no-user --time-style=iso --sort=ext --group-directories-first --color-scale all"
alias lnl="cpfg; eza --no-quotes -lX --icons --no-user --time-style=iso --sort=name --color-scale all"
alias lla="cpfg; eza --no-quotes -laX --icons --no-user --group-directories-first --sort=ext --time-style=iso --color-scale all"
alias lln="cpfg; eza --no-quotes -lX --icons --no-user --time-style=iso --sort=newest --color-scale all"
alias lls="cpfg; eza --no-quotes -lX --icons --no-user --time-style=iso --sort=size --group-directories-first --color-scale all"
alias llt="cpfg; eza --no-quotes -lX --icons --no-user --time-style=iso --sort=ext --group-directories-first --color-scale all --tree"
alias llg="cpfg; eza --no-quotes -lX --icons --no-user --time-style=iso --sort=ext --group-directories-first --color-scale all --git"
alias lld="cpfg; eza -DXl --icons --no-user --time-style=iso --sort=ext --group-directories-first --color-scale all"
alias llf="cpfg; eza -fXl --icons --no-user --time-style=iso --sort=ext --group-directories-first --color-scale all"

# package management
alias pacs="sudo pacman -S "
alias pacr="sudo pacman -Rns"
alias pacss="pacman -Ss"
alias pacsi="pacman -Si"
alias yays="yay --removemake -S"
alias yayss="yay -Ssa"
alias yaysi="yay -Si"
alias yaysc="yay -Sc"
alias syu="sudo pacman -Syu"
alias sua="yay --removemake -Sua"
alias tree="pactree -r "
alias align-mirrors="sudo pacman-mirrors --fasttrack && sudo pacman -Syyu"

# git
alias '..s'="git status"
alias '..d'="git diff"
alias '..p'="git push -u origin master"
alias '..m'="git push -u origin main"

# scripts 
alias fw='~/Repositories/scripts/frequent-words.sh'
alias tf='~/Repositories/scripts/music-tagger.sh'
alias zas='~/Repositories/scripts/active-study.sh'
alias gap='~/Repositories/scripts/active-projects.sh'
alias mvk="~/Repositories/scripts/mv-kebab.sh"
alias mvkr="~/Repositories/scripts/roll-thru-kebab.sh"
alias obo="~/Repositories/scripts/one-by-one.sh"
alias tagger="~/Repositories/scripts/tagger.sh"
alias gv="~/Repositories/scripts/convert-to-mp4.sh"
alias tn="~/Repositories/scripts/takenote.sh"
alias λ="~/Repositories/scripts/OpenShennong.sh"
alias knife='~/Repositories/scripts/kebab-knife.sh'
alias ⨯⨯⨯⨯="~/Repositories/scripts/trash-emptier.sh"
alias ¿="~/Repositories/scripts/system-check.sh"
alias tv="~/Repositories/scripts/upcoming-shows.sh"
alias clip="~/Repositories/scripts/video-clipper.sh"
alias unl="~/Repositories/scripts/update-newsletter.sh"
alias pall="~/Repositories/scripts/palladium.sh"
alias t="~/Repositories/scripts/world-clock.sh"
alias banna="~/Repositories/scripts/banna.sh"
alias sub="~/Repositories/scripts/subtitle-downloader.sh"
alias xv="~/Repositories/scripts/monet.sh"
alias lin="~/Repositories/scripts/huiyin.sh"

# files
alias ’z="e ~/Repositories/dotfiles/zsh/zshrc"
alias ’za="e ~/Repositories/dotfiles/zsh/aliases"
alias ’zf="e ~/Repositories/dotfiles/zsh/functions"
alias ’ze="e ~/Repositories/dotfiles/zsh/extra"
alias ’zv="e ~/Repositories/dotfiles/zsh/variables"

# misc aliases
alias '..'="cd .. && ll"
alias e="emacsclient -nw -a emacs"
alias q="source ~/.config/zsh/.zshrc; cpfg"
alias qq="clr; cd; cpfg; source ~/.config/zsh/.zshrc"
alias qqq="clr; cd; cpfg; source ~/.config/zsh/.zshrc; unl"
alias open="xdg-open"
alias fd="fd -i"
alias cp="cp -iv"
alias mv='mv -iv'
alias rm='rm -iv'
alias rmdir='rmdir -v'
alias grep='grep --color=auto -is'
alias window-name="xprop WM_CLASS"
alias clr="printf '\033[2J\033[3J\033[1;1H'"
alias memuse='df | grep sda1 | awk "{print \$5}" '
alias ,,='trans -b'
alias llwc="ll | wc -l"
alias back="~/Repositories/scripts/back/backmaster.sh"
alias morse="morse-x -f 350"
alias z="rdo zathura"
alias xvs="xv -d ~/Holding/screenshots"
alias ←n="xclip -selection clipboard"
alias ←="tr -d '\n' | xclip -selection clipboard"
alias sxiv="sxiv -a"
alias ytv="yt-dlp --fragment-retries infinite -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --no-mtime --embed-chapters"
alias ytm="yt-dlp --fragment-retries infinite --format bestaudio --no-mtime --extract-audio --audio-format mp3"
alias ytvr="yt-dlp --fragment-retries infinite -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --no-mtime --embed-chapters --sponsorblock-remove all"
alias ytmr="yt-dlp --fragment-retries infinite --format bestaudio --no-mtime --extract-audio --audio-format mp3 --sponsorblock-remove all"
alias duh="du -h"
alias rq="R -q -f "
alias rqq="R -s -f "
alias Q="R -s"
alias o="rdo okular"
alias cal="cal --color=always -3m"
alias f="fzf-dir && ll"
alias f~='hide_flag="-a"; f; hide_flag=""'
alias ff~='hide_flag="-a"; ff; hide_flag=""'
alias →="rsync -ParuL --"
alias ezad="ll -D"
alias ezaf="ll -f"
alias ⨯→="restore-files-from-trash"
alias ko="output-kebabized-string"
alias koc="copy-kebabized-string"
alias cpfg="change-prompt-for-git"
alias —="realpath"
alias znl="open-newsletter"
alias nnl="unread-newsletter"
alias shellcheck="shellcheck -e SC1111"
alias ййй="sudo ln -sf ~/Repositories/dotfiles/xkb/us ~/Repositories/dotfiles/xkb/ara /usr/share/X11/xkb/symbols/"
alias tt="tagutil"
