#!/bin/bash

# one_book_per_x_days: used in scripts/book-goal-calc.sh
export obpxd=60

# user-script data dir
export usdd="$HOME/.local/share/user-scripts"

# checked by battery-warner, 1 is on, 0 is off
export battery_warning_on=0

# trash directory
export TRASH_DIR="$HOME/.local/share/Trash/files"

# backup directory
export BACK_DIR="$HOME/Misc/Backups/"

# default prompt
export DEFAULT_PROMPT=" %F{#55ff55}%2~%f %S%F{#55ff55} 闯 %D{%H:%M} 🠦 %f%s "
export DEFAULT_PROMPT_SYMBOL="闯"
export DEFAULT_PROMPT_COLOR="#55ff55"
