#!/bin/bash

# one_book_per_x_days: used in scripts/book-goal-calc.sh
export obpxd=60

# user-script data dir
export usdd="$HOME/.local/share/user-scripts"

# checked by battery-warner, 1 is on, 0 is off
export battery_warning_on=1

# trash directory
export TRASH_DIR="$HOME/.local/share/Trash/files"

# backup directory
export BACK_DIR="$HOME/Misc/Backups/"

# default prompt
export DEFAULT_PROMPT_SYMBOL="宁"
export DEFAULT_PROMPT_COLOR="#55ff55"
export DEFAULT_PROMPT=" %F{$DEFAULT_PROMPT_COLOR}%2~%f %S%F{$DEFAULT_PROMPT_COLOR} $DEFAULT_PROMPT_SYMBOL %D{%H:%M} 🠦 %f%s "
