#!/bin/zsh
##################################################################################################
#
#					 ____  _   _    _    ____ ___     _____   _    ____  _____ 
#					/ ___|| | | |  / \  |  _ \_ _|   |__  /  / \  |  _ \| ____|
#					\___ \| |_| | / _ \ | | | | |_____ / /  / _ \ | | | |  _|  
#					 ___) |  _  |/ ___ \| |_| | |_____/ /_ / ___ \| |_| | |___ 
#					|____/|_| |_/_/   \_\____/___|   /____/_/   \_\____/|_____|
#
#					https://github.com/ShadiZade
#					.zshrc
#					zsh config
#
###################################################################################################
####### symlink location: ~/.config/zsh/ ##########################################################
source ~/.config/zsh/extra
source ~/.config/zsh/aliases
source ~/.config/zsh/functions
source ~/Misc/Backups/private-scripts/private-aliases.sh
PROMPT=' %F{#55ff55}%2~%f %S%F{#55ff55} 囍 %D{%H:%M} 🠦 %f%s '
detect-extra
[ "$extra_dirs_exist" = "y" ] || terminal-art
setxkbmap
export ZSH_COMPDUMP="$XDG_CACHE_HOME"/zsh/zcompdump-"$ZSH_VERSION" 
export HISTCONTROL=ignorespace
autoload -U compinit; compinit
# file location was changed from ~/.zshrc to ~/.config/zsh/.zshrc
# this was done by adding the following line to /etc/zsh/zshenv
# export ZDOTDIR="$HOME"/.config/zsh 
