#!/bin/zsh
##################################################################################################
#
#					 ____  _   _    _    ____ ___     _____   _    ____  _____ 
#					/ ___|| | | |  / \  |  _ \_ _|   |__  /  / \  |  _ \| ____|
#					\___ \| |_| | / _ \ | | | | |_____ / /  / _ \ | | | |  _|  
#					 ___) |  _  |/ ___ \| |_| | |_____/ /_ / ___ \| |_| | |___ 
#					|____/|_| |_/_/   \_\____/___|   /____/_/   \_\____/|_____|
#
#					https://github.com/ShadiZade
#					.zshrc
#					zsh config
#
###################################################################################################
####### symlink location: ~/.config/zsh/ ##########################################################

source ~/.config/zsh/extra-zsh-settings
PROMPT=' %F{#55ff55}%2~%f %S%F{#55ff55} 囍 %D{%H:%M} 🠦 %f%s '

# simple aliases
alias '..'="cd .. && ll"
alias '..2'="cd ../.."
alias '..3'="cd ../../.."
alias cdk="cd ~/Desktop && ll"
alias cdt="cd ~/.local/share/Trash/files && lln --time=changed --sort=changed && du -sh"
alias cdd="cd ~/Downloads && ll"
alias cdm="cd ~/Misc/Backups && ll"
alias cdb="cd ~/Books/add && ll"
alias cdc="cd ~/.config && l"
alias cds="cd ~/Study && ll"
alias cdsl="cd ~/Study/languages && ll"
alias cdsp="cd ~/Study/programming && ll"
alias cdrs="cd ~/Repositories/scripts && ll"
alias cdrd="cd ~/Repositories/dotfiles && ll"
alias cdrz="cd ~/Repositories/ShadiZade && ll"
alias cdwall="cd /usr/share/wallpapers/use && ll"
alias cdy="cd ~/Excluding/ytvid && lln"
alias rdol="rdo dolphin ."
alias rdold="rdo dolphin ~/Downloads"
alias rdols="rdol Holding/screenshots"
alias m="micro"
alias e="emacs -nw "
alias sm="sudo micro"
alias v="vim"
alias ff="ranger"
alias q="source ~/.config/zsh/.zshrc"
alias qq="clr; cd; ~/Repositories/scripts/terminal-art.sh"
alias qqq="clr; cd; source ~/.config/zsh/.zshrc"
alias xx="xdg-open"
alias mkdir="mkdir -pv"
alias fd="fd -i"
alias cp="cp -iv"
alias mv='mv -iv'
alias rmdir='rmdir -v'
alias grep='grep --color=auto -i'
alias window-name="xprop WM_CLASS"
alias pg='ping -c 1 gnu.org'
alias pg-c='while true; do ping -qc 1 gnu.org && break; sleep 3; done'
alias clr="printf '\033[2J\033[3J\033[1;1H'"
alias sudo='sudo '
alias sl='sl -eal5'
alias memuse='df | grep sda1 | awk "{print \$5}" '
alias ccat='highlight'
alias ,,='trans -b'
alias yd='calc "$(date +"%Y")-$1"'
alias llwc="ll | wc -l"
alias wi="nmcli device wifi"
alias back="~/Repositories/scripts/back/backmaster.sh"
alias morse="morse-x -f 350"
alias disk-destroyer="command dd"
alias dd="echo 'Probably the wrong command. Use alias \"disk-destroyer\" for the actual dd command.'"
alias mpv="rdo mpv"
alias mpa="command mpv --no-audio-display"
alias z="rdo zathura"
alias cf="~/Repositories/scripts/copy-full-path.sh" 
alias trash-clear="rm -rf ~/.local/share/Trash/files/*"

# translation
alias zhen="command trans -b zh:en"
alias enzh="command trans -b en:zh"
alias deen="command trans -b de:en"
alias ende="command trans -b en:de"
alias esen="command trans -b es:en"
alias enes="command trans -b en:es"
alias ruen="command trans -b ru:en"
alias enru="command trans -b en:ru"
alias laen="command trans -b la:en"
alias enla="command trans -b en:la"

# list
alias l="exa --icons --sort=ext --group-directories-first"
alias ll="exa -l --icons --no-user --time-style=iso --sort=ext --group-directories-first --color-scale"
alias lla="exa -la --icons --no-user --group-directories-first --sort=ext --time-style=iso --color-scale"
alias lln="exa -l --icons --no-user --time-style=iso --sort=newest --color-scale"
alias lls="exa -l --icons --no-user --time-style=iso --sort=size --group-directories-first --color-scale"

# package management
alias pacs="sudo pacman -S "
alias pacrsc="sudo pacman -Rsc"
alias pacr="sudo pacman -Rns"
alias pacss="pacman -Ss"
alias pacsi="pacman -Si"
alias yays="yay -S"
alias yayss="yay -Ssa"
alias yaysi="yay -Si"
alias yaysc="yay -Sc"
alias syu="sudo pacman -Syu"
alias sua="yay -Sua"
alias tree="pactree -r "
alias align-mirrors="sudo pacman-mirrors --fasttrack && sudo pacman -Syyu"

# ebooks
alias cdset="cd src/epub/text"


# git
alias gts="git status"
alias gtd="git diff"
alias gta="git add ."
alias gtc="git commit -m"
alias gtp="git push -u origin master"
alias gtp-main="git push -u origin main"

# scripts 
alias expact="~/Repositories/scripts/expact.sh"
alias expaca="~/Repositories/scripts/expaca.sh"
alias keys="~/Repositories/scripts/keys.sh"
alias font-list="~/Repositories/scripts/font-list.sh"
alias get-image="~/Repositories/scripts/extract-pdf-image.sh"
alias ytm="~/Repositories/scripts/ytmp3.sh"
alias ytr="~/Repositories/scripts/ytmp3-sb.sh"
alias ytv="~/Repositories/scripts/ytvid.sh"
alias knock="~/.local/share/knock/.knock/knock"
alias chcover="~/Repositories/scripts/chcover.sh"
alias newscript='which="script" ~/Repositories/scripts/new-micro.sh '
alias newsolution='which="solution" ~/Repositories/scripts/new-micro.sh '
alias newpbmodule='which="polybar-module" ~/Repositories/scripts/new-micro.sh '
alias newmotif="~/Repositories/scripts/newmotif.sh"
alias tess='~/Repositories/scripts/tess.sh'

# config files
### emacs
alias ’e="emacs -nw ~/Repositories/dotfiles/emacs/init.el"
### kitty 
alias ’k="micro ~/Repositories/dotfiles/kitty/kitty.conf"
### zsh
alias ’z="emacs -nw ~/Repositories/dotfiles/zsh/zshrc"
### awesomewm
alias ’a="emacs -nw ~/.config/awesome/rc.lua"
### bspwm
alias ’b="emacs -nw ~/Repositories/dotfiles/bspwm/bspwmrc"
alias ’s="micro ~/Repositories/dotfiles/sxhkd/sxhkdrc"
alias ’p="emacs -nw ~/Repositories/dotfiles/polybar/config.ini"
### theming
alias ’tc="emacs -nw ~/Repositories/scripts/bspwm-theme.sh"
alias ’tp="~/Repositories/scripts/theme-picker.sh"

# functions
## disown
function run_disowned() {
    "$@" & disown
}
function rdo() {
    # run_disowned and silenced

    run_disowned "$@" 1>/dev/null 2>/dev/null
}

## bigdate
bd () {
    date +"%Y%m%d%H%M"
}



# terminal art
~/Repositories/scripts/terminal-art.sh
setxkbmap

# set zcompdump location
compinit -d "$XDG_CACHE_HOME"/zsh/zcompdump-"$ZSH_VERSION" 



# file location was changed from ~/.zshrc to ~/.config/zsh/.zshrc
# this was done by adding the following line to /etc/zsh/zshenv
# export ZDOTDIR="$HOME"/.config/zsh 
