(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
(global-set-key (kbd "M-s M-s") 'complete-symbol)
(global-set-key (kbd "C-x C-,") 'eval-buffer)
(global-set-key (kbd "C-x w") 'shadi/load-elfeed)
(global-set-key (kbd "M-]") 'other-window)
(global-set-key (kbd "C-’ i") 'ispell-buffer)
(global-set-key (kbd "C-’ c") 'shadi/reload-config-file)
(global-set-key (kbd "C-’ r") 'rename-file)
(global-set-key (kbd "C-’ o") 'olivetti-mode)
(global-set-key (kbd "C-’ e i") 'shadi/edit-init)
(global-set-key (kbd "C-’ e f") 'shadi/edit-functions)
(global-set-key (kbd "C-’ e b") 'shadi/edit-bind)
(global-set-key (kbd "C-’ n") 'shadi/open-notes-dir)
(global-set-key (kbd "C-’ a l") 'shadi/arabic-font-large)
(global-set-key (kbd "C-’ a n") 'shadi/arabic-font-normal)
(global-set-key (kbd "C-’ f") 'shadi/fetch-events)
(global-set-key (kbd "C-c r") 'do-xhtml-refs)
(global-set-key (kbd "C-c b") 'do-xhtml-blockquote)
